"""alter table users

Revision ID: 0cbb3cbbc696
Revises:
Create Date: 2023-11-16 19:57:58.388074

"""
from typing import Sequence
from typing import Union

import fastapi_storages
import sqlalchemy as sa
from alembic import op
from db.users.models import storage
# revision identifiers, used by Alembic.

revision: str = "0cbb3cbbc696"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("login", sa.String(), nullable=False),
        sa.Column("password", sa.String(), nullable=False),
        sa.Column("nickname", sa.String(), nullable=True),
        sa.Column(
            "avatar",
            fastapi_storages.integrations.sqlalchemy.FileType(storage=storage),
            nullable=True,
        ),
        sa.Column("friends", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(["friends"], ["users.user_id"], ondelete="NO ACTION"),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_index(op.f("ix_users_login"), "users", ["login"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_login"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
