"""change file storage

Revision ID: 43a6dd44615e
Revises: 0cbb3cbbc696
Create Date: 2023-11-16 20:03:44.709802

"""
from typing import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "43a6dd44615e"
down_revision: Union[str, None] = "0cbb3cbbc696"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
